In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]
a1 = np.array(lista)
print(lista)
print(a1)
print(type(a1))

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
listb = [x for x in range(10)]
print(listb)

a2 = np.arange(10)
print(a2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
listc = [1, 1.0, 'abc']
print(listc)

a3 = np.array(listc)
print(a3)
print(a3.dtype)

[1, 1.0, 'abc']
['1' '1.0' 'abc']
<U32


In [9]:
listd = list('abcdefghijk')
print(listd)

a4 = np.array(listd)
print(a4)
print(a4[2])          # 'c'
print(a4[2:6])        # c d e f
print(a4[2:6:2])      # c e

print(a4[[1,7,5]])

filter1 = a4 > 'c'
#print(filter1)
print(a4[filter1])
print(a4[a4>'c'])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k']
c
['c' 'd' 'e' 'f']
['c' 'e']
['b' 'h' 'f']
['d' 'e' 'f' 'g' 'h' 'i' 'j' 'k']
['d' 'e' 'f' 'g' 'h' 'i' 'j' 'k']


In [10]:
a5 = np.arange(10, 20, 2)
print(a5)

a6 = np.arange(1.5, 2.5, 0.1)
print(a6)

[10 12 14 16 18]
[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]


In [11]:
a7 = np.linspace(1.5, 2.5, 10)
print(a7)

[1.5        1.61111111 1.72222222 1.83333333 1.94444444 2.05555556
 2.16666667 2.27777778 2.38888889 2.5       ]


In [13]:
a8 = np.zeros(5)
print(a8)
a8 = a8.astype(np.int64)
print(a8)

a9 = np.ones(10, dtype=np.int64)
print(a9)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


In [14]:
a10 = np.arange(5, 15)
print(a10)
print(a10.dtype)
print(a10.ndim)
print(a10.shape)
print(a10.size)

[ 5  6  7  8  9 10 11 12 13 14]
int64
1
(10,)
10


In [15]:
lista = [1,2,3,4]
listb = [10,20,30,40]

a1 = np.array(lista)
a2 = np.array(listb)
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 % a2)
print(  np.concatenate((a1, a2))    )

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]
[1 2 3 4]
[ 1  2  3  4 10 20 30 40]


In [16]:
print(a1)
print(sum(a1))        # python built-in
print(a1.sum())       # ndarray method
print(np.sum(a1))     # numpy function

[1 2 3 4]
10
10
10


In [17]:
import random

random.seed(224)
listr = [random.randint(10,100) for _ in range(10)]
print(listr)

# listr을 ndarray로 변환,
# - shape확인, sum, min, max, 표준편차 확인

a1 = np.array(listr)
print(np.sum(a1))
print(np.min(a1))
print(np.max(a1))
print(np.std(a1))
print(np.std(listr))

[18, 34, 69, 19, 78, 39, 22, 64, 94, 77]
514
18
94
26.706553502838965
26.706553502838965
