In [1]:
import numpy as np

In [2]:
lista = [[10, 20, 30],[40, 50 ,60]]

a1 = np.array(lista)
print(a1)

[[10 20 30]
 [40 50 60]]


In [9]:
# flatten, ravel - 2차원 배열을 1차원으로 바꿔주는 메소드

a2 = a1.flatten() # 1차로 바꿘 배열을 바꾸면 원래 2차원 배열의 값은 그대로 유지 - return copy(복사본에 작성)
print(a2)
a2[2] = 100
print(a2)
print(a1)
print('************')

a3 = a1.ravel() # 1차원으로 바뀐 배열을 바꾸면 원래 2차원 배열의 값도 바뀜 - return reference(원본에 작성)
print(a3)
a3[2] = 100
print(a3)
print(a1)

[10 20 30 40 50 60]
[ 10  20 100  40  50  60]
[[10 20 30]
 [40 50 60]]
************
[10 20 30 40 50 60]
[ 10  20 100  40  50  60]
[[ 10  20 100]
 [ 40  50  60]]


In [16]:
# concatenate
# numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind") - axis=0이 deflaut값이다.

a1 = np.arange(10,20).reshape(2,5)
a2 = np.arange(110,120).reshape(2,5)
print(a1, a1.shape)
print(a2, a2.shape)

a5 = np.concatenate((a1,a2), axis = 1) # axis = 1이면 옆으로, axis = 0 이면 밑으로 붙인다.
#np.hstack((a1,a2)) # axis = 1과 동일
#np.vstack((a1,a2)) # axis = 0 과 동일

[[10 11 12 13 14]
 [15 16 17 18 19]] (2, 5)
[[110 111 112 113 114]
 [115 116 117 118 119]] (2, 5)


In [26]:
print(a5)
np.hsplit(a5, 2) # 2로 하면 수평 방향으로 2개를 짤라준다.
#np.hsplit(a5, 5) # 5 - 5개로 짤라준다._ 밑에 것과 똑같은 역할을 해준다.
#a5[:, 2:4]
#a5[:, 4:6]
#a5[:, 6:8]
#a5[:, 8:10]
for i in range(0,9):
    print(a5[:, i*2:(i*2)+2])

[[ 10  11  12  13  14 110 111 112 113 114]
 [ 15  16  17  18  19 115 116 117 118 119]]
[[10 11]
 [15 16]]
[[12 13]
 [17 18]]
[[ 14 110]
 [ 19 115]]
[[111 112]
 [116 117]]
[[113 114]
 [118 119]]
[]
[]
[]
[]


In [30]:
a6 = a5.T
print(a6)
np.vsplit(a6, 5)

[[ 10  15]
 [ 11  16]
 [ 12  17]
 [ 13  18]
 [ 14  19]
 [110 115]
 [111 116]
 [112 117]
 [113 118]
 [114 119]]


[array([[10, 15],
        [11, 16]]),
 array([[12, 17],
        [13, 18]]),
 array([[ 14,  19],
        [110, 115]]),
 array([[111, 116],
        [112, 117]]),
 array([[113, 118],
        [114, 119]])]