In [1]:
import numpy as np

In [2]:
lista = [[1,2,10],[3,4,20]]
print(lista)

a1 = np.array(lista)
print(a1)
print(a1.ndim)
print(a1.shape)

[[1, 2, 10], [3, 4, 20]]
[[ 1  2 10]
 [ 3  4 20]]
2
(2, 3)


In [3]:
a2 = np.arange(10,20)
a2 = a2.reshape(2,5)
print(a2)
print(a2.shape)
print(a2.size)

[[10 11 12 13 14]
 [15 16 17 18 19]]
(2, 5)
10


In [4]:
listb = [[1,2,3], [4,5]]
print(listb)

a2 = np.array(listb)
print(a2)
print(a2.shape)

[[1, 2, 3], [4, 5]]
[list([1, 2, 3]) list([4, 5])]
(2,)


/tmp/ipykernel_8088/442986346.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array(listb)


In [5]:
a3 = np.arange(10,45).reshape(5,7)
print(a3)
#print(a3[3])
#print(a3[1:3])
#print(a3[3,5])
#print(a3[:,3:6])
#print(a3[1::2, :])
#print(a3[[1,3],:])
filter1 = a3[:, 0]%2==1
#print(a3[filter1])
print(a3[1:4, 1::2])

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
[[18 20 22]
 [25 27 29]
 [32 34 36]]


In [6]:
print(a3)
print(np.sum(a3))
print(np.sum(a3, axis = 1))
print(np.sum(a3, axis = 0))

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
945
[ 91 140 189 238 287]
[120 125 130 135 140 145 150]


In [7]:
print(a3)
print(a3.shape)
print(a3.T, a3.T.shape)

[[10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37]
 [38 39 40 41 42 43 44]]
(5, 7)
[[10 17 24 31 38]
 [11 18 25 32 39]
 [12 19 26 33 40]
 [13 20 27 34 41]
 [14 21 28 35 42]
 [15 22 29 36 43]
 [16 23 30 37 44]] (7, 5)
