In [11]:
import numpy as np

a1 = np.arange(30).reshape(5,6)
print(a1)

print('np.sum:', np.sum(a1, axis = 1)) # 행을 기준으로 더함

#add는 universal function이다., method = reduce
print(np.add.reduce(a1, axis = 1, where=a1%2==0)) #행을 기준으로 더하지만 조건 추가 가능 (where=a1%2==0), 짝수만 더하는 조건

#method = accumulate
print(np.add.accumulate(a1, axis = 1)) # axis=1을 기준으로 누적

#method = reduceat
print(np.add.reduceat(a1, [0,2,4], axis=1)) #[start, stop=start, stop]
#method = at
print(np.add.at(a1, [0,2,4], [10,20,30,40,50,60]))   # in-place axis=0을 따라 하나걸러 하나에 더해준다.
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
np.sum: [ 15  51  87 123 159]
[ 6 24 42 60 78]
[[  0   1   3   6  10  15]
 [  6  13  21  30  40  51]
 [ 12  25  39  54  70  87]
 [ 18  37  57  78 100 123]
 [ 24  49  75 102 130 159]]
[[ 1  5  9]
 [13 17 21]
 [25 29 33]
 [37 41 45]
 [49 53 57]]
None
[[10 21 32 43 54 65]
 [ 6  7  8  9 10 11]
 [22 33 44 55 66 77]
 [18 19 20 21 22 23]
 [34 45 56 67 78 89]]


In [15]:
a2 = np.arange(10)
a3 = np.arange(100,105)
print(a2, a2.shape)
print(a3, a3.shape)
#method = outer
a4 = np.add.outer(a2, a3)
print(a4, a4.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[100 101 102 103 104] (5,)
[[100 101 102 103 104]
 [101 102 103 104 105]
 [102 103 104 105 106]
 [103 104 105 106 107]
 [104 105 106 107 108]
 [105 106 107 108 109]
 [106 107 108 109 110]
 [107 108 109 110 111]
 [108 109 110 111 112]
 [109 110 111 112 113]] (10, 5)
